[daum_entertain_news_music]
title = "다음 연예 ─ 뉴스 ─ 뮤직"
url = "https://entertain.daum.net/news/music"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "p.desc_thumb"
waitUntil = "networkidle"

[daum_entertain_news_star]
title = "다음 연예 ─ 뉴스 ─ 스타"
url = "https://entertain.daum.net/news/star"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "p.desc_thumb"
waitUntil = "networkidle"

[daum_entertain_news_abroad]
title = "다음 연예 ─ 뉴스 ─ 해외"
url = "https://entertain.daum.net/news/abroad"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "p.desc_thumb"
waitUntil = "networkidle"

[naver_entertain_now_music]
title = "네이버 TV연예 ─ 최신뉴스 ─ 뮤직"
url = "https://entertain.naver.com/now?sid=7a5"
entrySelector = "ul.news_lst.news_lst2 li"
titleSelector = "a.tit"
linkSelector = "a"
contentSelector = "p.summary"
imageSelector = "a.thumb_area img"
waitUntil = "networkidle"

[naver_entertain_now_hot]
title = "네이버 TV연예 ─ 최신뉴스 ─ 연예가화제"
url = "https://entertain.naver.com/now?sid=221"
entrySelector = "ul.news_lst.news_lst2 li"
titleSelector = "a.tit"
linkSelector = "a"
contentSelector = "p.summary"
imageSelector = "a.thumb_area img"
waitUntil = "networkidle"

[naver_entertain_now_abroad]
title = "네이버 TV연예 ─ 최신뉴스 ─ 해외연예"
url = "https://entertain.naver.com/now?sid=309"
entrySelector = "ul.news_lst.news_lst2 li"
titleSelector = "a.tit"
linkSelector = "a"
contentSelector = "p.summary"
imageSelector = "a.thumb_area img"
waitUntil = "networkidle"
