[daum_entertain_news_music]
title = "다음 연예 ─ 뉴스 ─ 뮤직"
url = "https://entertain.daum.net/news/music"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "p.desc_thumb"
waitUntil = "networkidle"

[daum_entertain_news_star]
title = "다음 연예 ─ 뉴스 ─ 스타"
url = "https://entertain.daum.net/news/star"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "p.desc_thumb"
waitUntil = "networkidle"

[daum_entertain_news_abroad]
title = "다음 연예 ─ 뉴스 ─ 해외"
url = "https://entertain.daum.net/news/abroad"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "p.desc_thumb"
waitUntil = "networkidle"